【bugfix!!!】fbov&vpp bugfix
Co-authored-by: EX_mitsu<yangjie409@h-partners.com>



# message auto-generated for no-merge-commit merge:
!2935 merge master into master

【bugfix!!!】fbov&vpp bugfix

Created-by: EX_mitsuX
Commit-by: EX_mitsu
Merged-by: ascend-robot
Description: 本PR进行以下的bugfix:
<span style="color:#000000;">1.	VPP部分megaton bugfix。 （local variable 'output_tensor' referenced before assignment 问题）
  ![e0d3c1407e3c798d0bd59b15108ef485_914x57[1].png](https://raw.gitcode.com/user-images/assets/7404741/71d47dda-76ae-44c9-88d5-987055e6d409/e0d3c1407e3c798d0bd59b15108ef485_914x57_1_.png 'e0d3c1407e3c798d0bd59b15108ef485_914x57[1].png')
2.	融合算子BUG 重新设计流进行修复，略微提高permute融合算子条件下的计算性能（特定场景A3约0.6%，A2>1%。）。 RuntimeError: Rank 6, node localhost.localdomain, device 6, iteration 1: Unexpected result nan (message='found NaN in local forward loss calculation')，融合算子场景 TP1下 nan问题）
![3b766f137853c9af62ca4b32faaaf728_1338x53[1].png](https://raw.gitcode.com/user-images/assets/7404741/2e528efb-3d74-4b6f-be8a-ca51c90234f5/3b766f137853c9af62ca4b32faaaf728_1338x53_1_.png '3b766f137853c9af62ca4b32faaaf728_1338x53[1].png')
3.	添加拦截 GBS>1 * DP * PP * MBS（in VPP schedule with fb_overlap.）（'NoneType' object has no attribute '_base'；pop from empty list，pop及没有_base问题）
 ![6e0dba4e0d3eb8f8f32b6d9e0987ba83_814x52[1].png](https://raw.gitcode.com/user-images/assets/7404741/d4d38bdb-af5e-4fbf-9d10-706a4442293e/6e0dba4e0d3eb8f8f32b6d9e0987ba83_814x52_1_.png '6e0dba4e0d3eb8f8f32b6d9e0987ba83_814x52[1].png')
  ![621fddcb50b4a7339c244be5f527cdff_752x46[1].png](https://raw.gitcode.com/user-images/assets/7404741/ec8ac8ca-81ae-4561-b9dd-ce0bcc4057eb/621fddcb50b4a7339c244be5f527cdff_752x46_1_.png '621fddcb50b4a7339c244be5f527cdff_752x46[1].png')
4  添加拦截 noop layers 需要添加在模型尾部，（out._base is None, "counter-productive to free a view of another tensor." 空操作层问题）
  ![7713bb3da103d09fde25e6c14b6ecbc6_1044x55[1].png](https://raw.gitcode.com/user-images/assets/7404741/99afa9e4-3906-4d11-b9c2-a4b401d9821f/7713bb3da103d09fde25e6c14b6ecbc6_1044x55_1_.png '7713bb3da103d09fde25e6c14b6ecbc6_1044x55[1].png')
 5.修复了开启GEMM融合时，训练偶尔产生grad norm nan的BUG。********</span>


See merge request: Ascend/MindSpeed!2935